config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :users
  resources :tickets
  resources :cars

  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :car_type, :top_seat, :lower_seat, presence: true

  belongs_to :train
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true
  has_many :trains

  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes 

end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route
end

app/models/route.rb
class Route < ActiveRecord::Base 
  validates :title, presence: true

  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  
  has_many :trains
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :end_station, class_name: 'RailwayStation', foreign_key: :end_station_id
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :cars
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to @car
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:car_type, :top_seat, :lower_seat, :train_id)
  end
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  # GET /railway_stations
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  # PATCH/PUT /railway_stations/1
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to @railway_station, notice: 'Railway station was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /railway_stations/1
  def destroy
    @railway_station.destroy
    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:title, railway_station_ids: [])
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
    @sum_top_seat_pl = 0
    @sum_lower_seat_pl = 0
    @sum_top_seat_coupe = 0
    @sum_lower_seat_coupe = 0

    @train.cars.where(car_type: 'купе').each do |car|
      @sum_top_seat_coupe += car.top_seat
      @sum_lower_seat_coupe += car.lower_seat
    end

    @train.cars.where(car_type: 'плацкарт').each do |car|
      @sum_top_seat_pl += car.top_seat
      @sum_lower_seat_pl += car.lower_seat
    end
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new 
    end
  end

  def update
    
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.' 
    else
      render :edit 
    end
  end

  def destroy
    @train.destroy
      redirect_to trains_url, notice: 'Train was successfully destroyed.' 
    end
  end

  private

    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cars/_car.html.erb
<tr>
  <td><%=  %></td>
  <td><%= link_to 'Показать', car %></td>
  <td><%= link_to 'Редактировать', edit_car_path(car) %></td>
  <td><%= link_to 'Удалить', car, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <%= render 'common/errors', resource: @car %>  

  <div class="field">
    <%= f.label :car_type %>
    <%= f.text_field :car_type %>
  </div>

  <div class="field">
    <%= f.label :top_seat %>
    <%= f.number_field :top_seat %>
  </div>

  <div class="field">
    <%= f.label :lower_seat %>
    <%= f.number_field :lower_seat %>
  </div>

  <div class="field">
    <%= f.label :train, 'Номер поезда' %>
    <%= f.collection_select :train_id, Train.all, :id, :number %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @car.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Редактировать вагон</h1>

<%= render 'form', car: @car %>

<%= link_to 'Показать', @car %> |
<%= link_to 'Назад', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список вагонов</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @cars %>
  </tbody>
</table>

<br>

<%= link_to 'Создать вагон', new_car_path %>

app/views/cars/new.html.erb
<h1>Создать вагон</h1>

<%= render 'form', car: @car %>

<%= link_to 'Назад', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Тип вагона:</strong>
  <%= @car.car_type %>
</p>

<p>
  <strong>Количество верхних мест:</strong>
  <%= @car.top_seat %>
</p>

<p>
  <strong>Количество нижних мест:</strong>
  <%= @car.lower_seat %>
</p>

<%= link_to 'Редактировать', edit_car_path(@car) %> |
<%= link_to 'Назад', cars_path %>

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb
<p>
  <tr>
    <td>(c) 2017 pypok. Учебный проект</td>
      <a href="http://thinknetica.com">в школе Thinknetica.</a>
  </tr>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railway</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/railway_stations/_form.html.erb
<%= form_for(@railway_station) do |f| %>
  <%= render 'common/errors', resource: @railway_station %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @railway_station.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Показать', railway_station %></td>
  <td><%= link_to 'Редактировать', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Удалить', railway_station, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Показать', @railway_station %> |
<%= link_to 'Назад', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список станций</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'Создать станцию', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Редатировать', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Назад', railway_stations_path %>

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :railway_station_ids, 'Станции в маршруте' %>
    <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  
  <div class="actions">
    <%= f.submit "#{ @route.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Изменить маршрут</h1>

<%= render 'form' %>
<%= link_to 'Назад', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список маршрутов</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.title %></td>
        <td><%= link_to 'Показать', route %></td>
        <td><%= link_to 'Редактировать', edit_route_path(route) %></td>
        <td><%= link_to 'Удалить', route, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить маршрут', new_route_path %>

app/views/routes/new.html.erb
<h1>Создать маршрут</h1>

<%= render 'form' %>
<%= link_to 'Назад', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @route.title %>
</p>

<p>
  <strong>Список поездов на маршруте:</strong>
</p>
<p>
  <% if @route.trains.empty? %>
    Поездов на маршруте нет
  <% else %>
    <% @route.trains.each do |train| %>
      <li><%= train.number %></li>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Список станций в маршруте:</strong>
</p>
<p>
  <% if @route.railway_stations.empty? %>
    Станций в маршруте нет
  <% else %>
    <ul>
      <% @route.railway_stations.each do |station| %>
        <li><%= station.title %></li>
      <% end %>
    </ul>
  <% end %>
</p>



<%= link_to 'Редактировать', edit_route_path(@route) %> 
<%= link_to 'Назад', routes_path %>

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <%= render 'common/errors', resource: @train %>  
  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :current_station, 'Текущая станция' %>
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :route, 'Маршрут' %>
    <%= f.collection_select :route_id, Route.all, :id, :title %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @train.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Показать', train %></td>
  <td><%= link_to 'Редактировать', edit_train_path(train) %></td>
  <td><%= link_to 'Удалить', train, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Показать', @train %> |
<%= link_to 'Назад', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список поездов</h1>

<table>
  <thead>
    <tr>
      <th>Номер</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Создать поезд', new_train_path %>

app/views/trains/new.html.erb
<h1>Создать поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Назад', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер поезда:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>На станции:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Не указано
  <% end %>
</p>

<p>
  <strong>Назначен маршрут:</strong>
  <% if @train.route.present? %>
    <%= @train.route.title %>
  <% else %>
    Маршрут не назначен
  <% end %>
</p>

<p>
  <strong>Количество плацкартных вагонов:</strong>
  <%= @train.cars.where(car_type: 'плацкарт').size %> 
  <p>
    <strong>Количество верхних мест:</strong>
    <%= @sum_top_seat_pl %>
  </p>

  <p>
    <strong>Количество нижних мест:</strong>
    <%= @sum_lower_seat_pl %>
  </p>
</p>

<p>
  <strong>Количество купейных вагонов:</strong>
  <%= @train.cars.where(car_type: 'купе').size %>
  <p>
    <strong>Количество верхних мест:</strong>
    <%= @sum_top_seat_coupe %>
  </p>

  <p>
    <strong>Количество нижних мест:</strong>
    <%= @sum_lower_seat_coupe %>
  </p>
</p>

<%= link_to 'Редактировать', edit_train_path(@train) %> |
<%= link_to 'Назад', trains_path %>

app/views/welcome/index.html.erb
<h1>Привет, Rails!</h1>

<%= link_to 'Список станций', railway_stations_path %> 